### ISSUE TITLE
Test submission

### ISSUE THREAD

**Issue by iluvpool19** [hellofloat/float-programming-test#1]
https://github.com/iluvpool19/float-programming-test

**Comment by andyburke** [comment]
Thanks for this submission. Unfortunately it does not pass some of our more rigorous internal tests. We've updated our repo with some more guidance on submissions that might be worth looking at.

If you'd like to take another shot, push an update to your repo and re-open this issue.

Hint: It's worth adding some additional tests to exercise some of the edge cases. We also like to see people expand the limited tests we give by default.

**Comment by iluvpool19** [comment]
Do your tests involve time? Also, for balanced parens do you only want the
parentheses to  be balanced or curly braces and brackets as well?
(i.e. '( { [ ] } )' = true, '( [ ] } { )' = false). I also wasn't sure what
you wanted the return value to be in certain edge cases. Thanks.

-- 
Josh Apstein

**Comment by andyburke** [comment]
- No time-related tests currently.
- Only parens should count, you can ignore brackets and braces.

**Comment by iluvpool19** [comment]
I cannot re-open this issue because I am not a collaborator and I did not close it myself. However I have re-written some of my functions and written a lot of tests for edge cases. Thank you very much
