### ISSUE TITLE
Programming Test Updated

### ISSUE THREAD

**Issue by janeefongg** [hellofloat/float-programming-test#10]
Hello Andy,

Updates to the tests have been pulled to my fork. 
The functions have also been updated to reflect the newly implemented tests.
Here is the link to my fork: https://github.com/janeefongg/float-programming-test

If there is anything else, please feel free to let me know!

Sincerely,
Jane Fong

**Comment by andyburke** [comment]
Thanks for your submission, @janeefongg. All tests are passing.

Please email me at: andy at hellofloat.com

We will set up next steps.
