### ISSUE TITLE
[Update] Added additional tests

### ISSUE THREAD

**Issue by mtham8** [hellofloat/float-programming-test#11]
Hi Andy, 

Below is the url for my fork with updated tests:
https://github.com/mtham8/float-programming-test

Best, 
Michelle

**Comment by andyburke** [comment]
Hi @mtham8, unfortunately at this point some of our internal tests are still not passing around balanced parentheses. If you would like to continue, you are welcome to open up a new issue with a revised result, but we also realize that your time is valuable and understand if you do not wish to continue.

Thanks for your submissions!
