### ISSUE TITLE
Programming Test Submission

### ISSUE THREAD

**Issue by jshartshorn** [hellofloat/float-programming-test#19]
Ok,

I had time to get to this today. It could always be improved, but all solutions seem to test well:

https://github.com/jshartshorn/float-programming-test

Thanks,

Joel

**Comment by andyburke** [comment]
Thanks for this submission, just got back from vacation, sorry it took so long to get to this. Your solutions were good. Heard you accepted another position. Congrats! Sorry the timing didn't quite work out for us to move forward. Best of luck and keep us in mind if you're looking in the future.
