### ISSUE TITLE
Solve all problems

### ISSUE THREAD

**Issue by anatomij** [hellofloat/float-programming-test#2]
https://github.com/anatomij/float-programming-test

**Comment by andyburke** [comment]
Thanks for this submission. Unfortunately it does not pass some of our more rigorous internal tests. We've updated our repo with some more guidance on submissions that might be worth looking at.

If you'd like to take another shot, push an update to your repo and re-open this issue.

Hint: It's worth adding some additional tests to exercise some of the edge cases. We also like to see people expand the limited tests we give by default.
