### ISSUE TITLE
Submission

### ISSUE THREAD

**Issue by saronoff** [hellofloat/float-programming-test#20]
https://github.com/saronoff/float-programming-test

**Comment by andyburke** [comment]
Thanks for this submission, sorry it took a while to get back to you, I was out of the office.

Almost all our internal tests pass, but I would recommend considering the following string for the balanced parentheses test:

```
)()(
```

If you'd like to update your submission, just comment here once you've submitted your changes.

**Comment by saronoff** [comment]
Changes have been submitted.

**Comment by andyburke** [comment]
Thanks! We'll be in touch soon.
