### ISSUE TITLE
Code submitted

### ISSUE THREAD

**Issue by nirvanalabs** [hellofloat/float-programming-test#5]
Please find implemented code at

https://github.com/nirvanalabs/float-programming-test

**Comment by nirvanalabs** [comment]
I found one failed test case. Let's me fix it first

**Comment by andyburke** [comment]
Hello, could you reach out to me via email: andy at hellofloat.com

I can't link your github handle up with any of our current applicants.

**Comment by nirvanalabs** [comment]
Andy  When can we get an Update about this test Task?
