### ISSUE TITLE
Programming Test Complete

### ISSUE THREAD

**Issue by janeefongg** [hellofloat/float-programming-test#6]
Hello Andy Burke & Float Team,

I really appreciate the opportunity and the time you took out of your day to reach out!
I have looked into your company and am very interested in applying.

Here is the url to my fork: 
https://github.com/janeefongg/float-programming-test.git

I look forward to hearing back from you.
Thank you so much! Have a wonderful Wednesday!

Sincerely,
Jane Fong

**Comment by andyburke** [comment]
Thanks for the submission. A couple of our internal tests are failing on your submission. We usually recommend you add some additional test cases into the test suite to make sure all the APIs are behaving as expected.

I'm going to close the issue for now, but if you'd like to resubmit (and I would encourage you to), just update your branch and re-open this issue when you're ready.

Thanks!
