### ISSUE TITLE
[Complete] Programming Test

### ISSUE THREAD

**Issue by mtham8** [hellofloat/float-programming-test#7]
Hi Andy, 

Thank you for reaching out. I'm definitely interested in applying to Float.

Below is the url for my fork:
https://github.com/mtham8/float-programming-test

Have a great day!

Best, 
Michelle Tham

**Comment by andyburke** [comment]
Thanks for the submission. A handful of our internal tests are failing on your submission. We usually recommend you add some additional test cases into the test suite to make sure all the APIs are behaving as expected.

I'm going to close the issue for now, but if you'd like to resubmit (and I would encourage you to), just update your branch and re-open this issue when you're ready.

Thanks!
