### ISSUE TITLE
Programming Test Updated

### ISSUE THREAD

**Issue by janeefongg** [hellofloat/float-programming-test#9]
Thank you for the response and for your time!
I have refactored my code as well as updated my code to incorporate more in-depth tests.

Here is a link to my fork url:
https://github.com/janeefongg/float-programming-test

I look forward to hearing back from you again.

Sincerely,
Jane Fong

**Comment by andyburke** [comment]
Hi Jane,

I've updated our test with a couple more basic tests, you should merge upstream changes (https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/) and re-run the tests.

Andy
